/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js. It is committed here so type checking can
// run before the first local Next.js bootstrap.
